name: Build WAR File on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build WAR on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: Build WAR File
        run: mvn clean package -DskipTests

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-war
          path: target/*.war
