stages:
  - build

build_war:
  stage: build
  tags:
    - windows
  script:
    - echo "Checking out Repository..."
    - git checkout $CI_COMMIT_REF_NAME
    - echo "Setting up JDK 11..."
    - choco install openjdk11
    - echo "Building WAR File..."
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.war
